SET ZIPPATH=C:\Program Files\7-Zip
SET PGBIN=C:\path\to\bin
SET PGHOST=<server-base-ip>
SET PGPORT=5432
SET PGUSER=<user-base>
SET PGPASSWORD=<pass-base>
SET DBS=<db1>,<db2>,<db3>,<db4>,<db5>
SET BACKUPPATH=C:\path\to\backup
SET LATESTBACKUP=C:\path\to\base.backup
SET LOGPATH=\\place\for\logs